### ISSUE TITLE
Listening True-False reviews

### ISSUE THREAD

**Issue by dohee-koo** [danb-dliflc/GLOSSActivities#35]
I didn't repeat what was already discussed during the meeting. 

1. Titles are aligned/shifted to the left in Firefox; in Chrome and IE, they are centered.

2. "Questions" --> Developers don't give questions for this activity, so the word "questions" is not applicable here. "Statements" is the right term because this is a true/false activity.

3. Same for "View Questions" --> "View Questions" should be removed because there is no question; just by clicking "View Transcript" or "View Audio Hints", learners can switch windows, so "View Questions" may not be necessary. If you want to keep this for some reason, change this to "View Statements."

4. "Enable Alternate Audio" --> Checking or unchecking (whatever a student does) starts the audio; when does start what? not very intuitive

5. ps_ecn411 --> In the source, the translation is on the right (it should be on the left). In feedback, Pashto is aligned to the left. It should be aligned to the right. The original LO doesn't have this problem.

6. The audio player --> 1) When I move the red triangle to the left and click play, the audio plays unlimitedly; 2) when I move both the green triangle and red triangle and click play, the audio plays unlimitedly; 3) when I move only the green arrow and click play, the player behaves differently. It's hard to describe. Please test. I am pointing this out because I can't exactly figure out how this player works, which means, it's not very intuitive.

**Comment by wendy-dliflc** [comment]
1. Could you please take a look at the title in Firefox again? I recently made the change to center the Title, so I wonder if you may have tested in Firefox before I made the change and Chrome and IE after I made the change. If it's still not centered, you may have to clear your cache - I can come take a look if you want. Thanks!

**Comment by wendy-dliflc** [comment]
2, 3, 4 seem like design questions - should we discuss these? 

My thoughts/comments:
2. Changing "Questions" to "Statements" is fine with me. 

3. The reason for the "View Questions" button was because when there is both "View Transcript" and "View Audio Hints" the user can toggle between those two buttons by clicking on each, but they'd have to know to toggle both off to go back to the questions. I'm not sure if it's as intuitive without the "View Questions" (or "View Statements") button, but do others think it is intuitive enough without the button? Here's an example: 

http://gloss2.lingnet.org/HeadStartHtml/HeadStartHTML.html?disableBrowserLockout=true&gloss=true&glossLoXmlFileName=/HeadStartHtml/templates/linksLO/glossLOs/ger_cul429.xml&glossLoadActivityIndex=6&glossMediaPathRoot=http://gloss2.lingnet.org/products/gloss/

4.) To explain what it does - when it's not checked, it's the primary audio. When it's checked, it's the alternate audio. 

5 & 6 were moved to separate issues as they are not specific to this template.

**Comment by wendy-dliflc** [comment]
2.) Changed "Question" to "Statement"
3.) Changed "View Questions" to "View Statements"

**Comment by wendy-dliflc** [comment]
As discussed in meeting, changed "Statement" to "Statements" in the header of the table with the statements.
