### ISSUE TITLE
Listening True/False – Quiz Page

### ISSUE THREAD

**Issue by XiaomeiSchnittgrund** [danb-dliflc/GLOSSActivities#51]
Template’s name: Listening True/False – **Quiz Page**
Lessons tested: cm_mil236, cm_pol224, cm_sci404 and more; fr_cul425, fr_sci402; ars_cul444,ars_cul452; kp_cul257, kp_sci271; pf_soc444, pf_tec409; ru_cul433, and ru_soc227

Tested in IE11/10, Firefox, Chrome, but not Mac 
In **IE 11, Firefox** and **Chrome**, most of lessons work the same; I noticed that In **Firefox**, a video clip in act 4 of cm_mil236 doesn’t work, but works in **IE 11**
In **IE 10**, I couldn’t open any of the lesson’s **Quiz Page**.  See the capture below: 
 
Here are my observations: 
1.	Instructions are good. 100% correct answers will lead me to print out the Certificate.  
2.	Incorrect answers have me returning to the lesson’s **Overview Page**. 

         (Notes below are based upon not passing the Quiz)

3.	Then I went through each activity of all tested lessons **1)** some activities showed “Server Error page”, some were normal/working, but I couldn’t see the **Quiz Page** again; **2)** the same thing, some activities showed “errors”, others were working, but this time, I can ****retake** the Quiz. **3)** all of activities were working in two tested lessons, then I can see the Quiz; **4)** Accidently clicked a pjb_env_401 (I shouldn’t test this language),  but I found that this one doesn’t have the “Submit” button. See the capture:
 
4.	Some quizzes may not be workable; i.e.  one tested lesson, cm_tec404, I couldn’t do its quiz with current Instructions. I found that the quiz is activity 6, from its Instructions, one must look at two images (ads) while listening.  When this activity changes to Quiz, the Instruction changed and there are no images and the Quiz becomes unworkable. Both cm_tec406  and cm_soc442 are the same type of lessons as cm_tec404. _I believe such lessons (or similar LOs) exist in other languages too, but may not have exactly the same reasons_. 

5.	If the **Quiz** comes from the last activity of a lesson, then it’s a repeat activity; if the **Quiz** comes from activity 1, 2, 3 or 4, then the content of the lesson “Quiz” only reflects a small portion of the entire lesson (just a beginning of the audio or a warm up), so the meaning of the **Quiz** is very questionable.

Maybe we can either write a **Quiz** for each lesson or leave old lessons alone, starting next year, request that all developers write a quiz at the end of each **new** lesson. 

By the way, I have a question:  if one fails the quiz, must one go through all of activities (5/6) or just certain/selected activities? I checked all activities in each lesson, but there is no regular pattern.

The following comment should belong to testing **True/False_LC**  (activity), posted on 6/21.

Such lessons, like cm_tec404, cm_tec406 and cm_soc442 are becoming hard to make choices because the images /information are (in More Info.) **not** on the same page while listening. Certainly, this occurs in other languages as well.

**Comment by wendy-dliflc** [comment]
> 2.) Incorrect answers have me returning to the lesson’s Overview Page.

> 
Then I went through each activity of all tested lessons 1) some activities showed “Server Error page”, some were normal/working, but I couldn’t see the Quiz Page again; 2) the same thing, some activities showed “errors”, others were working, but this time, I can ***retake* the Quiz. 3) all of activities were working in two tested lessons, then I can see the Quiz; 4) Accidently clicked a pjb_env_401 (I shouldn’t test this language), but I found that this one doesn’t have the “Submit” button.

Response:
 The "Server Error" page is because some templates have not been converted - if you click on an activity that uses a template that hasn't been converted, then this message will appear. If the quiz is a template that has not been converted yet, then you'll see this message for the quiz as well. 

For pjb_env401, the "Submit" button for quizzes only appears on the last page/step. This activity has two steps, which is why you didn't see it when it first opened (because you're on the first step).

**Comment by XiaomeiSchnittgrund** [comment]
Hi Wendy,

Thank you for your explanations. I understood now.

xiaomei
-----Original Message-----

**Comment by wendy-dliflc** [comment]
After discussion with Julia, we will take Listening True False and Reading True False out as an option for Quiz. 

Xiaomei - to answer your question, after one fails the quiz, they must go through all of the activities to enable the Quiz again.

**Comment by XiaomeiSchnittgrund** [comment]
Thank you, Wendy. It's good to know. 

xiaomei

-----Original Message-----

**Comment by wendy-dliflc** [comment]
Updated so that quiz-mode for templates works in IE10.
